/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package KTGK;

import DB.DBQuery;
import Models.Friend;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author phatv
 */
public class AddFriends extends javax.swing.JFrame {

    private int user_id;
    private String username;

    DBQuery query = new DBQuery();
    DefaultListModel listRequests = new DefaultListModel();
    DefaultListModel listFriends = new DefaultListModel();
    private String hashRequests = "";
    private String hashFriends = "";

    /**
     * Creates new form AddFriends
     */
    public AddFriends() {
        initComponents();

//        new Thread(() -> {
//            while (true) {
//                ListRequests();
//                ListFriends();
//                try {
//                    Thread.sleep(3000);
//                } catch (InterruptedException ex) {
//                }
//            }
//        }).start();
    }

    public AddFriends(Dashboard dashboard) {
        this.user_id = dashboard.user_id;
        this.username = dashboard.username;

        initComponents();

        new Thread(() -> {
            while (true) {
                if (this.isVisible()) {
                    ListRequests();
                    ListFriends();
                }
                try {
                    Thread.sleep(1000);
                } catch (InterruptedException ex) {
                }
            }
        }).start();
    }

    private void ListRequests() {
        String hash = "";
        DefaultListModel list = new DefaultListModel();
        ResultSet rs = query.FriendRequest(user_id);
        try {
            while (rs.next()) {
                Friend f = new Friend(rs.getInt("id"), rs.getInt("user_id"), rs.getInt("friend_id"), rs.getInt("status"), rs.getString("username"));
                list.addElement(f);
                hash += f.toString();
            }
        } catch (SQLException ex) {
        }
        hash = Utils.hashMD5(hash);
        if (hashRequests.equals("") || !hashRequests.equals(hash)) {
            hashRequests = hash;
            listRequests.clear();
            listRequests = list;
            lstRequests.removeAll();
            lstRequests.setModel(list);
        }
    }

    private void ListFriends() {
        String hash = "";
        DefaultListModel list = new DefaultListModel();
        ResultSet rs = query.ListFriends(user_id);
        try {
            while (rs.next()) {
                Friend f = new Friend(rs.getInt("id"), rs.getInt("user_id"), rs.getInt("friend_id"), rs.getInt("status"), rs.getString("username"));
                list.addElement(f);
                hash += f.toString();
            }
        } catch (SQLException ex) {
        }
        hash = Utils.hashMD5(hash);
        if (hashFriends.equals("") || !hashFriends.equals(hash)) {
            hashFriends = hash;
            listFriends.clear();
            listFriends = list;
            lstFriends.removeAll();
            lstFriends.setModel(list);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtFr = new javax.swing.JTextField();
        btnFindAdd = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstRequests = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstFriends = new javax.swing.JList<>();
        btnAcceptFr = new javax.swing.JButton();
        btnDeleteFr = new javax.swing.JButton();
        btnDenyFr = new javax.swing.JButton();
        btnRefreshList = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Nhập ID hoặc Username để kết bạn:");

        btnFindAdd.setText("Tìm & Thêm bạn");
        btnFindAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindAddActionPerformed(evt);
            }
        });

        btnExit.setText("Thoát");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        jLabel2.setText("Yêu cầu kết bạn:");

        jScrollPane1.setViewportView(lstRequests);

        jLabel3.setText("Danh sách bạn bè:");

        jScrollPane2.setViewportView(lstFriends);

        btnAcceptFr.setText("Thêm bạn");
        btnAcceptFr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptFrActionPerformed(evt);
            }
        });

        btnDeleteFr.setText("Xoá bạn");
        btnDeleteFr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteFrActionPerformed(evt);
            }
        });

        btnDenyFr.setText("Xoá yêu cầu");
        btnDenyFr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDenyFrActionPerformed(evt);
            }
        });

        btnRefreshList.setText("Làm mới");
        btnRefreshList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshListActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtFr))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnFindAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExit))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnRefreshList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAcceptFr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDenyFr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDeleteFr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtFr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFindAdd)
                    .addComponent(btnExit))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRefreshList)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAcceptFr)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDenyFr)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDeleteFr))
                    .addComponent(jScrollPane2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnFindAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindAddActionPerformed
        String search = txtFr.getText();
        boolean isSuccess = false;

        try {
            int friend_id = Integer.parseInt(search);
            isSuccess = query.AddFriend(user_id, friend_id);
        } catch (NumberFormatException ex) {
            isSuccess = query.AddFriend(user_id, search);
        }

        if (isSuccess) {
            JOptionPane.showMessageDialog(null, "Đã gửi yêu cầu kết bạn.");
        } else {
            JOptionPane.showMessageDialog(null, "Không thể kết bạn.");
        }
    }//GEN-LAST:event_btnFindAddActionPerformed

    private void btnAcceptFrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptFrActionPerformed
        int i = lstRequests.getSelectedIndex();
        if (i >= 0) {
            Friend f = (Friend) listRequests.getElementAt(i);
//            System.out.println(f);
            query.AcceptRequest(f.id);
            ListRequests();
            ListFriends();
        }
    }//GEN-LAST:event_btnAcceptFrActionPerformed

    private void btnRefreshListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshListActionPerformed
        ListRequests();
        ListFriends();
    }//GEN-LAST:event_btnRefreshListActionPerformed

    private void btnDenyFrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDenyFrActionPerformed
        int i = lstRequests.getSelectedIndex();
        System.out.println(i);
        if (i >= 0) {
            Friend f = (Friend) listRequests.getElementAt(i);
            query.DenyRequest(f.id);
            ListRequests();
            ListFriends();
        }
    }//GEN-LAST:event_btnDenyFrActionPerformed

    private void btnDeleteFrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteFrActionPerformed
        int i = lstFriends.getSelectedIndex();
        System.out.println(i);
        if (i >= 0) {
            Friend f = (Friend) listFriends.getElementAt(i);
            query.DeleteFriend(f.id);
            ListRequests();
            ListFriends();
        }
    }//GEN-LAST:event_btnDeleteFrActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddFriends.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddFriends.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddFriends.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddFriends.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddFriends().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcceptFr;
    private javax.swing.JButton btnDeleteFr;
    private javax.swing.JButton btnDenyFr;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnFindAdd;
    private javax.swing.JButton btnRefreshList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> lstFriends;
    private javax.swing.JList<String> lstRequests;
    private javax.swing.JTextField txtFr;
    // End of variables declaration//GEN-END:variables
}
